#!/bin/bash
#SBATCH --nodes=1
#SBATCH --cpus-per-task=80
#SBATCH --time=30:00
#SBATCH --mem=180000mb
#SBATCH --export=ALL
#SBATCH -J amira_air
#SBATCH --array=0-14
#SBATCH --partition=dev_single
#KommentarSBATCH --gres=gpu:4

THREAD_LIMIT=40
RAND_SEED=112345 # RAND_SEED+start_at_image_number ist der genutzte Seed

#distractor within parts in air has SEED 012345
#distractor within parts on floor 0 has SEED 112345
#distractor within parts on floor 30 has SEED 212345
#distractor within parts on floor 60 has SEED 312345
#distractor within parts on floor 70 has SEED 412345
#distractor within parts on floor 80 has SEED 512345
#distractor within parts on top of another has SEED 612345

DEBUG_ABRGEN=True
COMPOSITIONS=280
IMAGE_COUNT=4
#number of images = COMPOSITIONS x SCENES x VIEWS

FORWARD_FRAMES=60
SCENE_TYPE="OwnScenariosDistractorWithinPartsInAir"
MODE="DISTRACTOR_WITHIN_PARTS_IN_AIR"

SAMPLES=8

USE_SPECIAL_DISTRIBUTION=True
MIN_TARGET_OBJECTS_PER_COMPOSITION=3
MAX_TARGET_OBJECTS_PER_COMPOSITION=9
MIN_DISTRACTOR_OBJECTS_PER_COMPOSITION=0
MAX_DISTRACTOR_OBJECTS_PER_COMPOSITION=6

#/pfs/data5/home/kit/anthropomatik/yc5412/sim2Real/amira
PATH_SCENE_TEMPLATE="$HOME/sim2Real/amira/distractor within parts in air/scene_template.blend"
PATH_CONFIG_TEMPLATE="$HOME/sim2Real/amira/config_template.cfg"
PATH_ABRGEN_FILE="$HOME/amira_blender_rendering/scripts/abrgen"
DIR_ABRGEN_SRC="$HOME/amira_blender_rendering/src/"
DIR_OUTPUT="$HOME/sim2Real/amira/distractor within parts in air/Output/"
DIR_TEMPORARY="$HOME/sim2Real/amira/distractor within parts in air/Temporary/"
DIR_TARGET_OBJECTS="$HOME/sim2Real/amira/partsTarget/"
DIR_DISTRACTOR_OBJECTS="$HOME/sim2Real/amira/partsDistractor/"
DIR_FLOOR_TEXTURES="$HOME/sim2Real/amira/textures/"
DIR_DISTRACTOR_TEXTURES="$HOME/sim2Real/amira/textures/"

START_AT_IMAGE_NUMBER="$((SLURM_ARRAY_TASK_ID*COMPOSITIONS+0))"

blender --background --python Script.py -- --DIR_DISTRACTOR_TEXTURES="$DIR_DISTRACTOR_TEXTURES" --DIR_FLOOR_TEXTURES="$DIR_FLOOR_TEXTURES" --FORWARD_FRAMES=$FORWARD_FRAMES --SCENE_TYPE="$SCENE_TYPE" --MODE="$MODE" --THREAD_LIMIT=$THREAD_LIMIT --RAND_SEED=$RAND_SEED --DEBUG_ABRGEN=$DEBUG_ABRGEN --COMPOSITIONS=$COMPOSITIONS --IMAGE_COUNT=$IMAGE_COUNT --SAMPLES=$SAMPLES --USE_SPECIAL_DISTRIBUTION=$USE_SPECIAL_DISTRIBUTION --MIN_TARGET_OBJECTS_PER_COMPOSITION=$MIN_TARGET_OBJECTS_PER_COMPOSITION --MAX_TARGET_OBJECTS_PER_COMPOSITION=$MAX_TARGET_OBJECTS_PER_COMPOSITION --MIN_DISTRACTOR_OBJECTS_PER_COMPOSITION=$MIN_DISTRACTOR_OBJECTS_PER_COMPOSITION --MAX_DISTRACTOR_OBJECTS_PER_COMPOSITION=$MAX_DISTRACTOR_OBJECTS_PER_COMPOSITION --PATH_SCENE_TEMPLATE="$PATH_SCENE_TEMPLATE" --PATH_CONFIG_TEMPLATE="$PATH_CONFIG_TEMPLATE" --PATH_ABRGEN_FILE="$PATH_ABRGEN_FILE" --DIR_ABRGEN_SRC="$DIR_ABRGEN_SRC" --DIR_OUTPUT="$DIR_OUTPUT" --DIR_TEMPORARY="$DIR_TEMPORARY" --DIR_TARGET_OBJECTS="$DIR_TARGET_OBJECTS" --DIR_DISTRACTOR_OBJECTS="$DIR_DISTRACTOR_OBJECTS" --START_AT_IMAGE_NUMBER=$START_AT_IMAGE_NUMBER
